[package]
name = "gtree"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
futures = "0.3"

itertools = "0.10"

gitlab = "0.1408"
graphql_client = "0.10"

git2 = { version = "0.13", features = ["vendored-libgit2", "vendored-openssl"] }

walkdir = "2"

async-trait = "*"

# Arg parsing and config
clap = { version = "3", features = ["derive"] }
figment = { version = "0.10", features = ["toml", "env"] }
serde = "1"

# logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-flame = "0.2"

# error handling
anyhow = "1"
thiserror = "1"

derivative = "2"

url = { version = "2", features = ["serde"] }
xdg = "2"

# terminal coloring
ansi_term = "0.12"
