### GQL_GITHUB_GET_PROJECTS

GRAPHQL https://api.github.com/graphql HTTP/1.1
Accept: application/json
Authorization: Bearer {{ $env.GITHUB_API_TOKEN }}

< ./github_projects_query.graphql

{
  "after": ""
}
